"""Initial migration

Revision ID: fb610ca399f7
Revises: 
Create Date: 2023-08-12 11:38:30.841156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb610ca399f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.drop_constraint('_student_grade_uc', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('grades', schema=None) as batch_op:
        batch_op.create_unique_constraint('_student_grade_uc', ['course_name', 'student_id'])

    # ### end Alembic commands ###
